### ISSUE TITLE
Unable to reproduce hash on local fork of repository

### ISSUE THREAD

**Issue by nathan-ahn** [ilijaNL/graphql-codegen-signed-operation#2]
I'm working on a pull request for #1 but am unable to reproduce the same hash for a single operation. 

Steps:
1. Clone this repository
2. `yarn install` and `yarn build`
3. Delete `graphql-codegen-signed-operation` directory in the relevant `node_modules` previously installed (by `npm install`)
4. Create a link to the local fork `ln -s ../../graphql-codegen-signed-operation`
5. Run `npx graphql-codegen --config codegen.ts`

I have about 28 hashes that are generated by this plugin and strangely enough, only a single one has a different hash when attempting to reproduce locally. Here's a copy of the definition:
```
export const UPDATE_CLIENT_PROFILE = gql`
	mutation UpdateClientProfile(
		$firstName: String
		$lastName: String
		$birthdate: AWSDate
	) {
		updateClientProfile(
			firstName: $firstName
			lastName: $lastName
			birthdate: $birthdate
		) {
			userId
			firstName
			lastName
			birthdate
		}
	}
`;
```

Deleting the link and reinstalling the package with `npm install` generates the old hash.

**Comment by ilijaNL** [comment]
Can you push the changes you want to make in your fork so i can see. Additionally you can write tests (see `/tests` directory) to cover your usecases.

**Comment by ilijaNL** [comment]
@nahn20 I created a new package which should give more flexibility to use your own gen function: https://github.com/ilijaNL/graphql-codegen-on-operations

This repository will be archived because of the new one
